

; BSD 3-Clause License
;
; Copyright 2024 Piyush Kumar, Da Eun Shim, Dongwon Jang, Azad Naeemi, or Georgia Institute of Technology
;
; Redistribution and use in source and binary forms, with or without 
; modification, are permitted provided that the following conditions are met:
;
; 1. Redistributions of source code must retain the above copyright notice, 
; this list of conditions and the following disclaimer.
;
; 2. Redistributions in binary form must reproduce the above copyright notice, 
; this list of conditions and the following disclaimer in the documentation 
; and/or other materials provided with the distribution.
;
; 3. Neither the name of the copyright holder nor the names of its contributors 
; may be used to endorse or promote products derived from this software without 
; specific prior written permission.
;
; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” 
; AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
; THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
; ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
; FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
; (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
; ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
; (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
; SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


;CONTROLS
;********************************
controls(

;techArray
techArray(
) ;techArray

;techParams
 techParams(
 ;( parameter           value )
 ;( ----------          ----- )
  ( maskGrid       	0.0005 )
  ( cadGrid        	0.0005 )
  ( drcGrid        	0.0005 )
  ( mfgGrid        	0.0005 )
  ( scale          	1.0 )
 ) ;techParams

;techPermissions
 techPermissions(
 ) ;techPermissions

;viewTypeUnits
 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
  ( maskLayout     	"micron"       	2000            )
  ( schematic      	"inch"         	160             )
  ( schematicSymbol	"inch"         	160             )
  ( netlist        	"inch"         	160             )
 ) ;viewTypeUnits

;mfgGridResolution
mfgGridResolution(
      ( 0.0005 )
 ) ;mfgGridResolution

;leMPPControls
;leMPPControls (

;leMPPDefinition
;leMPPDefinition (
;) ; MPP Definition

;leMPPRingObject
;leMPPRingObject (
;) ; MPP Ring Object

;leMPPMasterPath
;leMPPMasterPath (
;) ; Master Path

;leMPPEnclosedPath
;leMPPEnclosedPath (
;) ; Enclosed Path

;leMppOffsetPath
;leMppOffsetPath(
;); leMppOffsetPath

;leMPPSubRect - contacts
;leMPPSubRect (
;); leMPPSubRect

;leMPPEnclosedShape
;leMPPEnclosedShape (
;); leMPPEnclosedShape

;); leMPPControls
); controls

;LAYER DEFINITION
;********************************
layerDefinitions(
techPurposes(
;( purposeName  purposeNum   abbreviation )
;(   -----------        ----------        ----------     )
( color1           1          c1           )
) ;techPurposes


techLayers(
;( LayerName                 Layer#     Abbreviation )
;( ---------                 ------     ------------ )
;User-Defined Layers:
( NWELL                     1         NWELL       )
( ACT                       2         ACT        )
( GATE                      3         GATE        )
( DUMMY                     4         DUMMY       )
( GCUT                      5         GCUT       )
( NSEL                      6         NSEL       )
( PSEL                      7         PSEL        )
( BPR                       8         BPR        )
( VBPR                      9         VBPR        )
( SDCON                    10         SDCON          )
( VSD                      11         VSD          )
( VG                       12         VG          )
( M0                       20         M0          )
( M0text                   21         M0text      )
( V0                       22         V0          )
( M1                       25         M1          )
( M1text                   26         M1text      )
( V1                       27         V1          )
( M2                       30         M2          )
( M2text                   31         M2text      )
( V2                       32         V2          )
( M3                       35         M3          )
( M3text                   36         M3text      )
( V3                       37         V3          )
( M4                       40         M4          )
( M4text                   41         M4text      )
( V4                       42         V4          )
( M5                       45         M5          )
( M5text                   46         M5text      )
( V5                       47         V5          )
( M6                       50         M6          )
( M6text                   51         M6text      )
( V6                       52         V6          )
( M7                       55         M7          )
( M7text                   56         M7text      )
( V7                       57         V7          )
( M8                       60         M8          )
( M8text                   61         M8text      )
( V8                       62         V8          )
( M9                       65         M9          )
( M9text                   66         M9text      )
( V9                       67         V9          )
( M10                      70         M10         )
( M10text                  71         M10text     )
( V10                      72         V10         )
( M11                      75         M11         )
( M11text                  76         M11text     )
( V11                      77         V11         )
( M12                      80         M12         )
( M12text                  81         M12text     )
( V12                      82         V12         )
( M13                      85         M13         )
( M13text                  86         M13text     )
( V13                      87         V13         )
( RDL                      90         RDL         )
( ULVT                     95         ULVT        )
( LVT                      96         LVT         )
( SRAMVT                   98         SRAMVT      )
( BOUND                    110        BOUND       )
( snap                     233        snap         )
( prBoundary               235        prBndry      )
) ;techLayers

techLayerPurposePriorities(
;layers are ordered from lowest to highest priority
;( LayerName                 Purpose    )
;( ---------                 -------    )
( BPR                       drawing    )
( BPR                       label      )
( BPR                       pin        )
( BPR                       net        )
( VBPR                      drawing    )
( VBPR                      net        )
( NWELL                     drawing    )
( NWELL                     label      )
( NWELL                     pin        )
( NWELL                     net        )
( ACT                       drawing    )
( ACT                       net        )
( GATE                      drawing    )
( GATE                      label      )
( GATE                      pin        )
( GATE                      net        )
( GCUT                      drawing    )
( DUMMY                     drawing    )
( NSEL                      drawing    )
( PSEL                      drawing    )
( SDCON                     drawing    )
( SDCON                     net        )
( VSD                       drawing    )
( VSD                       net        )
( VG                        drawing    )
( VG                        net        )
( M0                        drawing    )
( M0                        label      )
( M0                        pin        )
( M0                        blockage   )
( M0                        net        )
( V0                        drawing    )
( V0                        blockage   )
( V0                        net        )
( M1                        drawing    )
( M1                        label      )
( M1                        pin        )
( M1                        blockage   )
( M1                        net        )
( V1                        drawing    )
( V1                        blockage   )
( V1                        net        )
( M2                        drawing    )
( M2                        label      )
( M2                        pin        )
( M2                        blockage   )
( M2                        net        )
( V2                        drawing    )
( V2                        blockage   )
( V2                        net        )
( M3                        drawing    )
( M3                        label      )
( M3                        pin        )
( M3                        blockage   )
( M3                        net        )
( V3                        drawing    )
( V3                        blockage   )
( V3                        net        )
( M4                        drawing    )
( M4                        label      )
( M4                        pin        )
( M4                        blockage   )
( M4                        net        )
( V4                        drawing    )
( V4                        blockage   )
( V4                        net        )
( M5                        drawing    )
( M5                        label      )
( M5                        pin        )
( M5                        blockage   )
( M5                        net        )
( V5                        drawing    )
( V5                        blockage   )
( V5                        net        )
( M6                        drawing    )
( M6                        label      )
( M6                        pin        )
( M6                        blockage   )
( M6                        net        )
( V6                        drawing    )
( V6                        blockage   )
( V6                        net        )
( M7                        drawing    )
( M7                        label      )
( M7                        pin        )
( M7                        blockage   )
( M7                        net        )
( V7                        drawing    )
( V7                        blockage   )
( V7                        net        )
( M8                        drawing    )
( M8                        label      )
( M8                        pin        )
( M8                        blockage   )
( M8                        net        )
( V8                        drawing    )
( V8                        blockage   )
( V8                        net        )
( M9                        drawing    )
( M9                        label      )
( M9                        pin        )
( M9                        blockage   )
( M9                        net        )
( V9                        drawing    )
( V9                        blockage   )
( V9                        net        )
( M10                       drawing    )
( M10                       label      )
( M10                       pin        )
( M10                       blockage   )
( M10                       net        )
( V10                       drawing    )
( V10                       blockage   )
( V10                       net        )
( M11                       drawing    )
( M11                       label      )
( M11                       pin        )
( M11                       blockage   )
( M11                       net        )
( V11                       drawing    )
( V11                       blockage   )
( V11                       net        )
( M12                       drawing    )
( M12                       label      )
( M12                       pin        )
( M12                       blockage   )
( M12                       net        )
( V12                       drawing    )
( V12                       blockage   )
( V12                       net        )
( M13                       drawing    )
( M13                       label      )
( M13                       pin        )
( M13                       blockage   )
( M13                       net        )
( V13                       drawing    )
( V13                       blockage   )
( V13                       net        )
( RDL                       drawing    )
( RDL                       label      )
( RDL                       pin        )
( RDL                       blockage   )
( RDL                       net        )
( M0text                    drawing    )
( M1text                    drawing    )
( M2text                    drawing    )
( M3text                    drawing    )
( M4text                    drawing    )
( M5text                    drawing    )
( M6text                    drawing    )
( M7text                    drawing    )
( M8text                    drawing    )
( M9text                    drawing    )
( M10text                   drawing    )
( M11text                   drawing    )
( M12text                   drawing    )
( M13text                   drawing    )
( prBoundary                drawing    )
( prBoundary                boundary   )
( BOUND                     drawing    )
( BOUND                     boundary   )
( snap                      drawing    )
( snap                      boundary   )
) ;techLayerPurposePriorities

techDisplays(
;( LayerName    	Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
;( ---------    	-------      ------          --- --- --------- ------- ----- )
( prBoundary   drawing      prBoundary       t t t t nil )
( prBoundary   boundary     prBoundaryBnd    t t t t nil )
( BPR          drawing      BPR_drg          t t nil nil t )
( BPR          label        BPR_lbl          t t nil nil t )
( BPR          pin          BPR_pin          t t nil nil t )
( BPR          net          BPR_net          t t nil nil t )
( VBPR         drawing      VBPR_drg         t t nil nil t )
( VBPR         net          VBPR_net         t t nil nil t )
( NWELL        drawing      NWELL_drg        t t nil nil t )
( NWELL        label        NWELL_lbl        t t nil nil t )
( NWELL        pin          NWELL_pin        t t nil nil t )
( NWELL        net          NWELL_net        t t nil nil t )
( ACT          drawing      ACT_drg          t t nil nil t )
( ACT          net          ACT_net          t t nil nil t )
( GATE         drawing      GATE_drg         t t nil nil t )
( GATE         label        GATE_lbl         t t nil nil t )
( GATE         pin          GATE_pin         t t nil nil t )
( GATE         net          GATE_net         t t nil nil t )
( GCUT         drawing      GCUT_drg         t t nil nil t )
( DUMMY        drawing      DUMMY_drg        t t nil nil t )
( NSEL         drawing      NSEL_drg         t t nil nil t )
( PSEL         drawing      PSEL_drg         t t nil nil t )
( SDCON        drawing      SDCON_drg        t t nil nil t )
( SDCON        net          SDCON_net        t t nil nil t )
( VSD          drawing      VSD_drg          t t nil nil t )
( VSD          net          VSD_net          t t nil nil t )
( VG           drawing      VG_drg           t t nil nil t )
( VG           net          VG_net           t t nil nil t )
( M0           drawing      M0_drg           t t nil nil t )
( M0           label        M0_lbl           t t nil nil t )
( M0           pin          M0_pin           t t nil nil t )
( M0           blockage     M0_blk           nil t nil nil t )
( M0           net          M0_net           t t nil nil t )
( V0           drawing      V0_drg           t t nil nil t )
( V0           blockage     V0_blk           nil t nil nil t )
( V0           net          V0_net           t t nil nil t )
( M1           drawing      M1_drg           t t nil nil t )
( M1           label        M1_lbl           t t nil nil t )
( M1           pin          M1_pin           t t nil nil t )
( M1           blockage     M1_blk           nil t nil nil t )
( M1           net          M1_net           t t nil nil t )
( V1           drawing      V1_drg           t t nil nil t )
( V1           blockage     V1_blk           nil t nil nil t )
( V1           net          V1_net           t t nil nil t )
( M2           drawing      M2_drg           t t nil nil t )
( M2           label        M2_lbl           t t nil nil t )
( M2           pin          M2_pin           t t nil nil t )
( M2           blockage     M2_blk           nil t nil nil t )
( M2           net          M2_net           t t nil nil t )
( V2           drawing      V2_drg           t t nil nil t )
( V2           blockage     V2_blk           nil t nil nil t )
( V2           net          V2_net           t t nil nil t )
( M3           drawing      M3_drg           t t nil nil t )
( M3           label        M3_lbl           t t nil nil t )
( M3           pin          M3_pin           t t nil nil t )
( M3           blockage     M3_blk           nil t nil nil t )
( M3           net          M3_net           t t nil nil t )
( V3           drawing      V3_drg           t t nil nil t )
( V3           blockage     V3_blk           nil t nil nil t )
( V3           net          V3_net           t t nil nil t )
( M4           drawing      M4_drg           t t nil nil t )
( M4           label        M4_lbl           t t nil nil t )
( M4           pin          M4_pin           t t nil nil t )
( M4           blockage     M4_blk           nil t nil nil t )
( M4           net          M4_net           t t nil nil t )
( V4           drawing      V4_drg           t t nil nil t )
( V4           blockage     V4_blk           nil t nil nil t )
( V4           net          V4_net           t t nil nil t )
( M5           drawing      M5_drg           t t nil nil t )
( M5           label        M5_lbl           t t nil nil t )
( M5           pin          M5_pin           t t nil nil t )
( M5           blockage     M5_blk           nil t nil nil t )
( M5           net          M5_net           t t nil nil t )
( V5           drawing      V5_drg           t t nil nil t )
( V5           blockage     V5_blk           nil t nil nil t )
( V5           net          V5_net           t t nil nil t )
( M6           drawing      M6_drg           t t nil nil t )
( M6           label        M6_lbl           t t nil nil t )
( M6           pin          M6_pin           t t nil nil t )
( M6           blockage     M6_blk           nil t nil nil t )
( M6           net          M6_net           t t nil nil t )
( V6           drawing      V6_drg           t t nil nil t )
( V6           blockage     V6_blk           nil t nil nil t )
( V6           net          V6_net           t t nil nil t )
( M7           drawing      M7_drg           t t nil nil t )
( M7           label        M7_lbl           t t nil nil t )
( M7           pin          M7_pin           t t nil nil t )
( M7           blockage     M7_blk           nil t nil nil t )
( M7           net          M7_net           t t nil nil t )
( V7           drawing      V7_drg           t t nil nil t )
( V7           blockage     V7_blk           nil t nil nil t )
( V7           net          V7_net           t t nil nil t )
( M8           drawing      M8_drg           t t nil nil t )
( M8           label        M8_lbl           t t nil nil t )
( M8           pin          M8_pin           t t nil nil t )
( M8           blockage     M8_blk           nil t nil nil t )
( M8           net          M8_net           t t nil nil t )
( V8           drawing      V8_drg           t t nil nil t )
( V8           blockage     V8_blk           nil t nil nil t )
( V8           net          V8_net           t t nil nil t )
( M9           drawing      M9_drg           t t nil nil t )
( M9           label        M9_lbl           t t nil nil t )
( M9           pin          M9_pin           t t nil nil t )
( M9           blockage     M9_blk           nil t nil nil t )
( M9           net          M9_net           t t nil nil t )
( V9           drawing      V9_drg           t t nil nil t )
( V9           blockage     V9_blk           nil t nil nil t )
( V9           net          V9_net           t t nil nil t )
( M10          drawing      M10_drg          t t nil nil t )
( M10          label        M10_lbl          t t nil nil t )
( M10          pin          M10_pin          t t nil nil t )
( M10          blockage     M10_blk          nil t nil nil t )
( M10          net          M10_net          t t nil nil t )
( V10          drawing      V10_drg          t t nil nil t )
( V10          blockage     V10_blk          nil t nil nil t )
( V10          net          V10_net          t t nil nil t )
( M11          drawing      M11_drg          t t nil nil t )
( M11          label        M11_lbl          t t nil nil t )
( M11          pin          M11_pin          t t nil nil t )
( M11          blockage     M11_blk          nil t nil nil t )
( M11          net          M11_net          t t nil nil t )
( V11          drawing      V11_drg          t t nil nil t )
( V11          blockage     V11_blk          nil t nil nil t )
( V11          net          V11_net          t t nil nil t )
( M12          drawing      M12_drg          t t nil nil t )
( M12          label        M12_lbl          t t nil nil t )
( M12          pin          M12_pin          t t nil nil t )
( M12          blockage     M12_blk          nil t nil nil t )
( M12          net          M12_net          t t nil nil t )
( V12          drawing      V12_drg          t t nil nil t )
( V12          blockage     V12_blk          nil t nil nil t )
( V12          net          V12_net          t t nil nil t )
( M13          drawing      M13_drg          t t nil nil t )
( M13          label        M13_lbl          t t nil nil t )
( M13          pin          M13_pin          t t nil nil t )
( M13          blockage     M13_blk          nil t nil nil t )
( M13          net          M13_net          t t nil nil t )
( V13          drawing      V13_drg          t t nil nil t )
( V13          blockage     V13_blk          nil t nil nil t )
( V13          net          V13_net          t t nil nil t )
( RDL          drawing      RDL_drg          t t nil nil t )
( RDL          label        RDL_lbl          t t nil nil t )
( RDL          pin          RDL_pin          t t nil nil t )
( RDL          blockage     RDL_blk          nil t nil nil t )
( RDL          net          RDL_net          t t nil nil t )
( M0text       drawing      M0_txt           t t nil nil t )
( M1text       drawing      M1_txt           t t nil nil t )
( M2text       drawing      M2_txt           t t nil nil t )
( M3text       drawing      M3_txt           t t nil nil t )
( M4text       drawing      M4_txt           t t nil nil t )
( M5text       drawing      M5_txt           t t nil nil t )
( M6text       drawing      M6_txt           t t nil nil t )
( M7text       drawing      M7_txt           t t nil nil t )
( M8text       drawing      M8_txt           t t nil nil t )
( M9text       drawing      M9_txt           t t nil nil t )
( M10text      drawing      M10_txt          t t nil nil t )
( M11text      drawing      M11_txt          t t nil nil t )
( M12text      drawing      M12_txt          t t nil nil t )
( M13text      drawing      M13_txt          t t nil nil t )
( BOUND        drawing      BOUND_drg        t t nil nil t )
( BOUND        boundary     BOUND_bnd        t t nil nil t )
( snap         drawing      snap             t t t t nil )
( snap         boundary     snap             t nil t t nil)
) ;techDisplays

;techLayerProperties
; techLayerProperties(
; ;( PropName               Layer1 [ Layer2 ]            PropValue )
; ;( --------               ------ ----------            --------- )
; ) ;techLayerProperties

;techDerivedLayers
; techDerivedLayers(
;;( DerivedLayerName          #          composition  )
;;( ----------------          ------     ------------ )
; ) ;techDerivedLayers

) ;layerDefinitions

;LAYER RULES
;********************************
layerRules(

;functions
 functions(
 ;( layer 			function        [maskNumber])
 ;( ----- 			--------        ------------)
  ( NWELL			"nWell"             1            )
  ( ACT			        "diffusion"         2            )
  ( GATE                    	"poly"              3            )
  ( DUMMY                    	"recognition"       4            )
  ( GCUT                    	"recognition"       5            )
  ( NSEL                    	"recognition"       6            )
  ( PSEL                    	"recognition"       7            )
  ( BPR			        "metal"             8            )
  ( VBPR			"contactlessMetal"  9            )
  ( SDCON			"contactlessMetal"  10           )
  ( VSD 			"contactlessMetal"  11           )
  ( VG   			"contactlessMetal"  12           )
  ( M0                   	"metal"     	    20           )
  ( V0                    	"cut"       	    22           )
  ( M1                   	"metal"     	    25           )
  ( V1                    	"cut"       	    27           )
  ( M2                   	"metal"     	    30           )
  ( V2                    	"cut"       	    32           )
  ( M3                   	"metal"     	    35           )
  ( V3                    	"cut"       	    37           )
  ( M4                   	"metal"     	    40           )
  ( V4                    	"cut"       	    42           )
  ( M5                   	"metal"     	    45           )
  ( V5                    	"cut"       	    47           )
  ( M6                   	"metal"     	    50           )
  ( V6                    	"cut"       	    52           )
  ( M7                   	"metal"     	    55           )
  ( V7                    	"cut"       	    57           )
  ( M8                   	"metal"     	    60           )
  ( V8                    	"cut"       	    62           )
  ( M9                   	"metal"     	    65           )
  ( V9                    	"cut"       	    67           )
  ( M10                   	"metal"     	    70           )
  ( V10                    	"cut"       	    72           )
  ( M11                   	"metal"     	    75           )
  ( V11                    	"cut"       	    77           )
  ( M12                   	"metal"     	    80           )
  ( V12                    	"cut"       	    82           )
  ( M13                   	"metal"     	    85           )
  ( V13                    	"cut"       	    87           )
  ( RDL                   	"metal"     	    90           )
  ( ULVT                   	"other"     	    95           )
  ( LVT                   	"other"     	    96           )
  ( SRAMVT                   	"other"     	    98           )
  ( BOUND                   	"other"     	    110          )
 ) ;functions

;mfgResolutions
 mfgResolutions(
 ;( layer                  mfgResolution )
 ;( -----                  ------------- )
  ( NWELL                    	0.0005 )
  ( ACT                     	0.0005 )
  ( GATE                        0.0005 )
  ( DUMMY                       0.0005 )
  ( GCUT                        0.0005 )
  ( NSEL                        0.0005 )
  ( PSEL                        0.0005 )
  ( BPR                         0.0005 )
  ( VBPR                      	0.0005 )
  ( SDCON                       0.0005 )
  ( VSD                         0.0005 )
  ( VG                          0.0005 )
  ( M0                   	0.0005 )
  ( V0                    	0.0005 )
  ( M1                   	0.0005 )
  ( V1                    	0.0005 )
  ( M2                   	0.0005 )
  ( V2                    	0.0005 )
  ( M3                   	0.0005 )
  ( V3                    	0.0005 )
  ( M4                   	0.0005 )
  ( V4                    	0.0005 )
  ( M5                   	0.0005 )
  ( V5                    	0.0005 )
  ( M6                   	0.0005 )
  ( V6                    	0.0005 )
  ( M7                   	0.0005 )
  ( V7                    	0.0005 )
  ( M8                   	0.0005 )
  ( V8                    	0.0005 )
  ( M9                   	0.0005 )
  ( V9                    	0.0005 )
  ( M10                   	0.0005 )
  ( V10                    	0.0005 )
  ( M11                   	0.0005 )
  ( V11                    	0.0005 )
  ( M12                   	0.0005 )
  ( V12                    	0.0005 )
  ( M13                   	0.0005 )
  ( V13                    	0.0005 )
  ( RDL                   	0.0005 )
  ( ULVT                  	0.0005 )
  ( LVT                  	0.0005 )
  ( SRAMVT                 	0.0005 )
  ( BOUND                 	0.0005 )
 ) ;mfgResolutions

;routingDirections
 routingDirections( ;( layer                       direction     )
 ;( -----                       ---------     )
  ( M0 horizontal )
  ( M1 vertical   )
  ( M2 horizontal )
  ( M3 vertical   )
  ( M4 horizontal )
  ( M5 vertical   )
  ( M6 horizontal )
  ( M7 vertical   )
  ( M8 horizontal )
  ( M9 vertical   )
  ( M10 horizontal )
  ( M11 vertical   )
  ( M12 horizontal )
  ( M13 vertical   )
  ( RDL horizontal )
 ) ;routingDirections
) ;layerRules

;VIADEFS
;********************************
viaDefs(

standardViaDefs(
( via13       	M13     RDL      	(V13 0.056 0.056 0)    (1 1 (0.056 0.056))     (0.000 0.012)	(0.012 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via12_13      M12     M13      	(V12 0.056 0.056 0)    (1 1 (0.056 0.056))     (0.012 0.000)	(0.000 0.012)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via11_12      M11     M12      	(V11 0.056 0.056 0)    (1 1 (0.056 0.056))     (0.000 0.012)	(0.012 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via10_11      M10     M11      	(V10 0.056 0.056 0)    (1 1 (0.056 0.056))     (0.012 0.000)	(0.000 0.012)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via9_10       M9      M10      	(V9 0.038 0.056 0)     (1 1 (0.038 0.056))     (0.000 0.010)	(0.010 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via89       	M8      M9      	(V8 0.038 0.038 0)     (1 1 (0.038 0.038))     (0.008 0.000)	(0.000 0.008)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via78       	M7      M8      	(V7 0.038 0.038 0)     (1 1 (0.038 0.038))     (0.000 0.008)	(0.008 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via67       	M6      M7      	(V6 0.038 0.038 0)     (1 1 (0.038 0.038))     (0.008 0.000)	(0.000 0.008)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via56       	M5      M6      	(V5 0.021 0.038 0)     (1 1 (0.021 0.038))     (0.000 0.006)	(0.006 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via45       	M4      M5      	(V4 0.021 0.021 0)     (1 1 (0.021 0.021))     (0.005 0.000)	(0.000 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via34       	M3      M4      	(V3 0.014 0.021 0)     (1 1 (0.014 0.021))     (0.000 0.004)	(0.004 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via23       	M2      M3      	(V2 0.014 0.012 0)     (1 1 (0.014 0.012))     (0.004 0.000)	(0.000 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via12       	M1      M2      	(V1 0.014 0.012 0)     (1 1 (0.014 0.012))     (0.000 0.004)	(0.004 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( via01       	M0      M1      	(V0 0.014 0.012 0)     (1 1 (0.014 0.012))     (0.004 0.000)	(0.000 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( diffCont    	SDCON   M0      	(VSD 0.013 0.012 0)    (1 1 (0.029 0.012))     (0.001 0.000)	(0.004 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
( polyCont    	GATE    M0      	(VG 0.015 0.012 0)     (1 1 (0.027 0.012))     (0.000 0.004)	(0.004 0.000)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)  )
) ;standardViaDefs

);viaDefs

;CONSTRAINT GROUPS
;********************************
constraintGroups (
( foundry

spacings(
    ( minWidth                   "NWELL"   0.042 )
    ( minSpacing                 "NWELL"   0.042 )
    ( minArea                    "NWELL"   0.003024  )
    ( minWidth                   "ACT"     0.010 )
    ( minSpacing                 "ACT"     0.030 )
    ( minArea                    "ACT"     0.00042 )
    ( minWidth                   "GATE"    0.015 )
    ( minSpacing                 "GATE"    0.027 )
    ( minArea                    "GATE"    0.006 )
    ( minWidth                   "M0"      0.012  )
    ( minSpacing                 "M0"      0.012  )
    ( minArea                    "M0"      0.000288 )
    ( minWidth                   "V0"      0.012 )
    ( minSpacing                 "V0"      0.012 )
    ( minWidth                   "M1"      0.014  )
    ( minSpacing                 "M1"      0.014  )
    ( minArea                    "M1"      0.000392 )
    ( minWidth                   "V1"      0.012 )
    ( minSpacing                 "V1"      0.012 )
    ( minWidth                   "M2"      0.012  )
    ( minSpacing                 "M2"      0.012  )
    ( minArea                    "M2"      0.000288 )
    ( minWidth                   "V2"      0.012 )
    ( minSpacing                 "V2"      0.012 )
    ( minWidth                   "M3"      0.014  )
    ( minSpacing                 "M3"      0.014  )
    ( minArea                    "M3"      0.000392 )
    ( minWidth                   "V3"      0.012 )
    ( minSpacing                 "V3"      0.012 )
    ( minWidth                   "M4"      0.021  )
    ( minSpacing                 "M4"      0.021  )
    ( minArea                    "M4"      0.000693 )
    ( minWidth                   "V4"      0.021 )
    ( minSpacing                 "V4"      0.021 )
    ( minWidth                   "M5"      0.021  )
    ( minSpacing                 "M5"      0.021  )
    ( minArea                    "M5"      0.000693 )
    ( minWidth                   "V5"      0.021 )
    ( minSpacing                 "V5"      0.021 )
    ( minWidth                   "M6"      0.038  )
    ( minSpacing                 "M6"      0.038  )
    ( minArea                    "M6"      0.002052 )
    ( minWidth                   "V6"      0.038 )
    ( minSpacing                 "V6"      0.038 )
    ( minWidth                   "M7"      0.038  )
    ( minSpacing                 "M7"      0.038  )
    ( minArea                    "M7"      0.002052 )
    ( minWidth                   "V7"      0.038 )
    ( minSpacing                 "V7"      0.038 )
    ( minWidth                   "M8"      0.038  )
    ( minSpacing                 "M8"      0.038  )
    ( minArea                    "M8"      0.002052 )
    ( minWidth                   "V8"      0.038 )
    ( minSpacing                 "V8"      0.038 )
    ( minWidth                   "M9"      0.038  )
    ( minSpacing                 "M9"      0.038  )
    ( minArea                    "M9"      0.002204 )
    ( minWidth                   "V9"      0.038 )
    ( minSpacing                 "V9"      0.038 )
    ( minWidth                   "M10"     0.056  )
    ( minSpacing                 "M10"     0.056  )
    ( minArea                    "M10"     0.00448 )
    ( minWidth                   "V10"     0.056 )
    ( minSpacing                 "V10"     0.056 )
    ( minWidth                   "M11"     0.056  )
    ( minSpacing                 "M11"     0.056  )
    ( minArea                    "M11"     0.00448 )
    ( minWidth                   "V11"     0.056 )
    ( minSpacing                 "V11"     0.056 )
    ( minWidth                   "M12"     0.360  )
    ( minSpacing                 "M12"     0.360  )
    ( minArea                    "M12"     0.1944 )
    ( minWidth                   "V12"     0.056 )
    ( minSpacing                 "V12"     0.056 )
    ( minWidth                   "M13"     0.360  )
    ( minSpacing                 "M13"     0.360  )
    ( minArea                    "M13"     0.1944 )
    ( minWidth                   "V13"     0.056 )
    ( minSpacing                 "V13"     0.056 )
    ( minWidth                   "RDL"     1.600  )
    ( minSpacing                 "RDL"     1.600  )
    ( minArea                    "RDL"     3.84 )
) ;spacings

;orderedSpacings
;    orderedSpacings(
;    ) ;orderedSpacings

;electrical
;    electrical(
;    ;( constraint		layer1	[layer2]	value  )
;    ;( ----------		------	--------	-----  )
;    ) ;electrical

;orderedElectrical
;    orderedElectrical(
;    ;( constraint		layer1	layer2	value  )
;    ;( ----------		------	------	------  )
;    ) ;orderedElectrical

interconnect(
( validRoutingLayers   ( V13 V12 V11 V10 V9 V8  V7  V6  V5  V4  V3  V2  V1 V0 RDL M13 M12 M11 M10 M9  M8  M7  M6  M5 M4  M3  M2  M1 M0 VG VSD GATE SDCON BPR VBPR ) )
) ;interconnect
) ;foundry

( LEFDefaultRouteSpec   nil
( horizontalRouteGridPitch 	M0              	 0.024 )
( verticalRouteGridPitch 	        M0              	 0.024 )
( horizontalRouteGridOffset 	M0              	 0.012 )
( verticalRouteGridOffset 	        M0              	 0.012 )
( minWidth         		M0              	 0.012 )
( minWidth         		V0              	 0.012 )
( horizontalRouteGridPitch 	M1              	 0.028 )
( verticalRouteGridPitch 	        M1              	 0.028 )
( horizontalRouteGridOffset 	M1              	 0.014 )
( verticalRouteGridOffset 	        M1              	 0.014 )
( minWidth         		M1              	 0.014 )
( minWidth         		V1              	 0.012 )
( horizontalRouteGridPitch 	M2              	 0.024 )
( verticalRouteGridPitch 	        M2              	 0.024 )
( horizontalRouteGridOffset 	M2              	 0.012 )
( verticalRouteGridOffset 	        M2              	 0.012 )
( minWidth         		M2              	 0.012 )
( minWidth         		V2              	 0.012 )
( horizontalRouteGridPitch 	M3              	 0.028 )
( verticalRouteGridPitch 	        M3              	 0.028 )
( horizontalRouteGridOffset 	M3              	 0.014 )
( verticalRouteGridOffset 	        M3              	 0.014 )
( minWidth         		M3              	 0.014 )
( minWidth         		V3              	 0.014 )
( horizontalRouteGridPitch 	M4              	 0.042 )
( verticalRouteGridPitch 	        M4              	 0.042 )
( horizontalRouteGridOffset 	M4              	 0.021 )
( verticalRouteGridOffset 	        M4              	 0.021 )
( minWidth         		M4              	 0.021 )
( minWidth         		V4              	 0.021 )
( horizontalRouteGridPitch 	M5              	 0.042 )
( verticalRouteGridPitch 	        M5              	 0.042 )
( horizontalRouteGridOffset 	M5              	 0.021 )
( verticalRouteGridOffset 	        M5              	 0.021 )
( minWidth         		M5              	 0.021 )
( minWidth         		V5              	 0.021 )
( horizontalRouteGridPitch 	M6              	 0.076 )
( verticalRouteGridPitch 	        M6              	 0.076 )
( horizontalRouteGridOffset 	M6              	 0.038 )
( verticalRouteGridOffset 	        M6              	 0.038 )
( minWidth         		M6              	 0.038 )
( minWidth         		V6              	 0.038 )
( horizontalRouteGridPitch 	M7              	 0.076 )
( verticalRouteGridPitch 	        M7              	 0.076 )
( horizontalRouteGridOffset 	M7              	 0.038 )
( verticalRouteGridOffset 	        M7              	 0.038 )
( minWidth         		M7              	 0.038 )
( minWidth         		V7              	 0.038 )
( horizontalRouteGridPitch 	M8              	 0.076 )
( verticalRouteGridPitch 	        M8              	 0.076 )
( horizontalRouteGridOffset 	M8              	 0.038 )
( verticalRouteGridOffset 	        M8              	 0.038 )
( minWidth         		M8              	 0.038 )
( minWidth         		V8              	 0.038 )
( horizontalRouteGridPitch 	M9              	 0.076 )
( verticalRouteGridPitch 	        M9              	 0.076 )
( horizontalRouteGridOffset 	M9              	 0.038 )
( verticalRouteGridOffset 	        M9              	 0.038 )
( minWidth         		M9              	 0.038 )
( minWidth         		V9              	 0.038 )
( horizontalRouteGridPitch 	M10              	 0.112 )
( verticalRouteGridPitch 	        M10              	 0.112 )
( horizontalRouteGridOffset 	M10              	 0.056 )
( verticalRouteGridOffset 	        M10              	 0.056 )
( minWidth         		M10              	 0.056 )
( minWidth         		V10              	 0.056 )
( horizontalRouteGridPitch 	M11              	 0.112 )
( verticalRouteGridPitch 	        M11              	 0.112 )
( horizontalRouteGridOffset 	M11              	 0.056 )
( verticalRouteGridOffset 	        M11              	 0.056 )
( minWidth         		M11              	 0.056 )
( minWidth         		V11              	 0.056 )
( horizontalRouteGridPitch 	M12              	 0.720 )
( verticalRouteGridPitch 	        M12              	 0.720 )
( horizontalRouteGridOffset 	M12              	 0.360 )
( verticalRouteGridOffset 	        M12              	 0.360 )
( minWidth         		M12              	 0.360 )
( minWidth         		V12              	 0.056 )
( horizontalRouteGridPitch 	M13              	 0.720 )
( verticalRouteGridPitch 	        M13              	 0.720 )
( horizontalRouteGridOffset 	M13              	 0.360 )
( verticalRouteGridOffset 	        M13              	 0.360 )
( minWidth         		M13              	 0.360 )
( minWidth         		V13              	 0.056 )
( horizontalRouteGridPitch 	RDL              	 3.200 )
( verticalRouteGridPitch 	        RDL              	 3.200 )
( horizontalRouteGridOffset 	RDL              	 1.600 )
( verticalRouteGridOffset 	        RDL              	 1.600 )
( minWidth         		RDL              	 1.600 )
( validRoutingLayers 	 (M0 M1 M2   M3   M4  M5  M6  M7  M8  M9 M10 M11 M12 M13 RDL))
( validRoutingVias 	 (via01 via12 via23 via34 via45 via56 via67 via78 via89 via9_10 via10_11 via11_12 via12_13 via13 polyCont diffCont  ))
);LEFDefaultRouteSpec
) ;constraintGroups

;STREAM LAYER MAPPING
;********************************
streamLayerMapping (
( NWELL       drawing     1       0 )
( NWELL	      net         1        3 )
( NWELL	      blockage    1        4 )
( NWELL       label       1       20 )
( NWELL       pin         1       251 )
( ACT         drawing     2       0 )
( ACT	      net         2        3 )
( ACT	      blockage    2        4 )
( ACT         label       2       20 )
( ACT         pin         2       251 )
( GATE        drawing     3       0 )
( GATE	      net         3        3 )
( GATE	      blockage    3        4 )
( GATE        label       3       20 )
( GATE        pin         3       251 )
( DUMMY       drawing     4       0 )
( DUMMY	      net         4        3 )
( DUMMY	      blockage    4        4 )
( DUMMY       label       4       20 )
( DUMMY       pin         4       251 )
( GCUT        drawing     5       0 )
( GCUT	      net         5        3 )
( GCUT	      blockage    5        4 )
( GCUT        label       5       20 )
( GCUT        pin         5       251 )
( NSEL        drawing     6       0 )
( NSEL	      net         6        3 )
( NSEL	      blockage    6        4 )
( NSEL        label       6       20 )
( NSEL        pin         6       251 )
( PSEL        drawing     7       0 )
( PSEL	      net         7        3 )
( PSEL	      blockage    7        4 )
( PSEL        label       7       20 )
( PSEL        pin         7       251 )
( BPR         drawing     8       0 )
( BPR	      net         8        3 )
( BPR	      blockage    8        4 )
( BPR         label       8       20 )
( BPR         pin         8       251 )
( VBPR        drawing     9       0 )
( VBPR	      net         9        3 )
( VBPR	      blockage    9        4 )
( VBPR        label       9       20 )
( VBPR        pin         9       251 )
( SDCON       drawing     10      0 )
( SDCON	      net         10       3 )
( SDCON	      blockage    10       4 )
( SDCON       label       10      20 )
( SDCON       pin         10      251 )
( VSD         drawing     11      0 )
( VSD 	      net         11       3 )
( VSD	      blockage    11       4 )
( VSD         label       11      20 )
( VSD         pin         11      251 )
( VG          drawing     12      0 )
( VG	      net         12       3 )
( VG	      blockage    12       4 )
( VG          label       12      20 )
( VG          pin         12      251 )
( M0          drawing     20      0 )
( M0	      net         20       3 )
( M0	      blockage    20       4 )
( M0          label       20      20 )
( M0          pin         20      251 )
( V0          drawing     22      0 )
( V0	      net         22       3 )
( V0	      blockage    22       4 )
( V0          label       22      20 )
( V0          pin         22      251 )
( M1          drawing     25      0 )
( M1	      net         25       3 )
( M1	      blockage    25       4 )
( M1          label       25      20 )
( M1          pin         25      251 )
( V1          drawing     27      0 )
( V1	      net         27       3 )
( V1	      blockage    27       4 )
( V1          label       27      20 )
( V1          pin         27      251 )
( M2          drawing     30      0 )
( M2	      net         30       3 )
( M2	      blockage    30       4 )
( M2          label       30      20 )
( M2          pin         30      251 )
( V2          drawing     32      0 )
( V2	      net         32       3 )
( V2	      blockage    32       4 )
( V2          label       32      20 )
( V2          pin         32      251 )
( M3          drawing     35      0 )
( M3	      net         35       3 )
( M3	      blockage    35       4 )
( M3          label       35      20 )
( M3          pin         35      251 )
( V3          drawing     37      0 )
( V3	      net         37       3 )
( V3	      blockage    37       4 )
( V3          label       37      20 )
( V3          pin         37      251 )
( M4          drawing     40      0 )
( M4	      net         40       3 )
( M4	      blockage    40       4 )
( M4          label       40      20 )
( M4          pin         40      251 )
( V4          drawing     42      0 )
( V4	      net         42       3 )
( V4	      blockage    42       4 )
( V4          label       42      20 )
( V4          pin         42      251 )
( M5          drawing     45      0 )
( M5	      net         45       3 )
( M5	      blockage    45       4 )
( M5          label       45      20 )
( M5          pin         45      251 )
( V5          drawing     47      0 )
( V5	      net         47       3 )
( V5	      blockage    47       4 )
( V5          label       47      20 )
( V5          pin         47      251 )
( M6          drawing     50      0 )
( M6	      net         50       3 )
( M6	      blockage    50       4 )
( M6          label       50      20 )
( M6          pin         50      251 )
( V6          drawing     52      0 )
( V6	      net         52       3 )
( V6	      blockage    52       4 )
( V6          label       52      20 )
( V6          pin         52      251 )
( M7          drawing     55      0 )
( M7	      net         55       3 )
( M7	      blockage    55       4 )
( M7          label       55      20 )
( M7          pin         55      251 )
( V7          drawing     57      0 )
( V7	      net         57       3 )
( V7	      blockage    57       4 )
( V7          label       57      20 )
( V7          pin         57      251 )
( M8          drawing     60      0 )
( M8	      net         60       3 )
( M8	      blockage    60       4 )
( M8          label       60      20 )
( M8          pin         60      251 )
( V8          drawing     62      0 )
( V8	      net         62       3 )
( V8	      blockage    62       4 )
( V8          label       62      20 )
( V8          pin         62      251 )
( M9          drawing     65      0 )
( M9	      net         65       3 )
( M9	      blockage    65       4 )
( M9          label       65      20 )
( M9          pin         65      251 )
( V9          drawing     67      0 )
( V9	      net         67       3 )
( V9	      blockage    67       4 )
( V9          label       67      20 )
( V9          pin         67      251 )
( M10         drawing     70      0 )
( M10	      net         70       3 )
( M10	      blockage    70       4 )
( M10         label       70      20 )
( M10         pin         70      251 )
( V10         drawing     72      0 )
( V10	      net         72       3 )
( V10	      blockage    72       4 )
( V10         label       72      20 )
( V10         pin         72      251 )
( M11         drawing     75      0 )
( M11	      net         75       3 )
( M11	      blockage    75       4 )
( M11         label       75      20 )
( M11         pin         75      251 )
( V11         drawing     77      0 )
( V11	      net         77       3 )
( V11	      blockage    77       4 )
( V11         label       77      20 )
( V11         pin         77      251 )
( M12         drawing     80      0 )
( M12	      net         80       3 )
( M12	      blockage    80       4 )
( M12         label       80      20 )
( M12         pin         80      251 )
( V12         drawing     82      0 )
( V12 	      net         82       3 )
( V12	      blockage    82       4 )
( V12         label       82      20 )
( V12         pin         82      251 )
( M13         drawing     85      0 )
( M13	      net         85       3 )
( M13	      blockage    85       4 )
( M13         label       85      20 )
( M13         pin         85      251 )
( V13         drawing     87      0 )
( V13	      net         87       3 )
( V13	      blockage    87       4 )
( V13         label       87      20 )
( V13         pin         87      251 )
( RDL         drawing     90      0 )
( RDL	      net         90       3 )
( RDL	      blockage    90       4 )
( RDL         label       90      20 )
( RDL         pin         90      251 )
( prBoundary  drawi	  235     0 )
( Bound	      drawing	  110     0 )
( snap	      drawing	  233     0 )
) ;streamLayerMapping
